### ISSUE TITLE
Disconnect jabber

### ISSUE THREAD

**Issue by sebest06** [no-go/NotifyRelay#10]
Hello, i am using this application in an android 4.4.2 (Tablet) with jabber account to send to other jabber account. The app run very well, send all notifications. But when i leave the tablet for a long time, (+3hs) the jabber client disconnects and the app not send more notifications.

**Comment by no-go** [comment]
I'm very sorry to hear that. I'd like to argue that it's due to the tablet's power-saving mode, but when a message is received from the tablet (and displayed as a notification), the app's "service" must also become active. Maybe the Internet is not available at that moment. Maybe the Jabber service provider also wants a new session ID.... Maybe...

Unfortunately, there are too many places that could explain this behavior. For this I should absolutely add a kind of "event"-logging. I have been neglecting this in my apps. I hope to have the time in a few weeks to add this Log to the app for a better error-handling on the user and programmer side.

Translated with www.DeepL.com/Translator

**Comment by sebest06** [comment]
Hi. i continued to use the app, and i see that the problems may be is the power manger... others apps do the same problem... 

By the way when a notification came the app run well. 

I have a doubt because i see the client disconneted from my clien roster, but when a notification came it user is logged again and run well. Is that ok?. I will continuos to use the app and i will report you if i see a problem.

Thanks

**Comment by no-go** [comment]
I am happy to hear this. In the past (<2008) jabber had problems with the "away" or "logged in" status. The status update in jabber did not do a good job.

I is nice to see, that you detect a "disconnect" when it realy occours. It is fine, that your device and the app do its job, reconnect and send the message.

:o)

Maybe there is a "ping" the App could send to the jabber server, but I think, this would not stop any powersave functions of your device 🤔

**Comment by sebest06** [comment]
Ok, great!

I think you can close the issue

Thanks!

**Comment by no-go** [comment]
you are welcome
